---
# Settings to determine the reader settings
reader:
  channel_select: 0 # Specify channel to review (False for all channels, -1 for last channel, 0, 1, 2 for respective channels, etc)
  resilience: True # Test for resilience (run binarization code)
  flow: True # Test for flow (run optical flow code)
  coarsening: True # Test for coarsening (run intensity distribution comparison code)
  verbose: True # Provide information for time elapsed while processing file, current channel, etc
  return_graphs: True # Provides grapsh for further examination of each file
  accept_dim_images: True # Runs code on dim images, can give inaccurate results
  accept_dim_channels: True # Runs code on dim channels, can give inaccurate results
  exclude_directories: # Directories/folders to be excluded from search, remove directories to search all files
    directory2: "Aditya"
    directory3: "htp-screening"
    
  

# Settings to determine resilience parameters
resilience_parameters:
  r_offset: 0 # Binarization threshold (calculated as (1 + r_offset) * mean)
  percent_threshold:
    percent_threshold_loss: 0.9 # Minimum percentage of original area to be considered persistent
    percent_threshold_gain: 1.1 # Maximum percentage of original area to be considered persistent
  frame_step: 1 # Step/percent of video between frames to analyse; enter decimal for percentage of video to skip between evaluated frames, integer for number of frames between evaluated frames
  evaluation_settings:
    frame_start_percent: 0.9 # Percentage of the video to start calculating final persistence metrics
    frame_stop_percent: 1 # Percentage of the video to stop calculation of final persistence metrics

# Settings to determine flow parameters
flow_parameters:
  min_corr_len: 25
  min_fraction: 0.5
  frame_step: 20 # Step/percent of video between frames for flow fields; enter decimal for percentage of video, integer for number of frames
  downsample: 8
  pixel_size: 1
  bin_width: 1

# Settings to determine coarsening parameters
coarse_parameters:
  evaluation_settings:
    first_frame: 0 # First frame to measure intensity distribution for intensity difference calculations
    last_frame: False # Last frame to measure intensity distribution for intensity difference calcuations; use None to select last frame of video, otherwise type in number to select a final frame
  threshold_percentage: 6 # Threshold percentage for comparison in mean-mode differences between first and last frames; adjust for different objective lenses (5-7 for 60x, 1 for 20x, etc)
  mean_mode_frames_percent: 10 # Percentage of frames to use for mean-mode comparison
  
writer:
  use_dataset_to_normalize: False # Use dataset limits to establish normalization bounds for barcode generation, otherwise use default values
  generate_rgb_map: False # Generate the color code for each image, WIP
  generate_barcode: True # Generate the barcode for each image, WIP