---
# Settings to determine the reader settings
reader:
  channel_select: -1
  resilience: True
  flow: True
  coarsening: True
  verbose: True
  accept_dim_images: True

# Settings to determine resilience parameters
resilience_parameters:
  r_offset: 0
  percent_threshold:
    percent_threshold_loss: 0.9
    percent_threshold_gain: 1.1
  frame_step: 1
  evaluation_settings:
    frame_start_percent: 0.9
    frame_stop_percent: 1

# Settings to determine flow parameters
flow_parameters:
  min_corr_len: 25
  min_fraction: 0.5
  frame_step: 1
  downsample: 8
  pixel_size: 1
  bin_width: 1

# Settings to determine coarsening parameters
coarse_parameters:
  evaluation_settings:
    first_frame: 0
    last_frame: False
  threshold_percentage: 1
  