---
# Settings to determine the reader settings
reader:
  channel_select: -1
  resilience: True
  flow: True
  coarsening: True
  verbose: True
  accept_dim_images: False
  accept_dim_channels: False

# Settings to determine resilience parameters
resilience_parameters:
  r_offset: 0
  percent_threshold:
    percent_threshold_loss: 0.9
    percent_threshold_gain: 1.1
  frame_step: 1
  evaluation_settings:
    frame_start_percent: 0.9
    frame_stop_percent: 1

# Settings to determine flow parameters
flow_parameters:
  frame_step: 20
  downsample: 8

# Settings to determine coarsening parameters
coarse_parameters:
  evaluation_settings:
    first_frame: 0
    last_frame: False
  threshold_percentage: 6 # Adjust for different objective lenses (5-7 for 60x, 1 for 20x, etc)
  mean_mode_frames_percent: 10
  
